# output paths for hydra logs
run:
  dir: logs/runs/${model.model}/${datamodule.name}/${now:%Y-%m-%d_%H-%M}
sweep:
  dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
job:
  env_set:
    EXAMPLE_VAR: "example_value"