_target_: src.models.NFVAE

D: 1

data_shape: [1]

encoder_configs:
  architecture: fcn
  hidden_sizes: [10]
  dim_input: 1
  activation: elu

decoder_configs:
  architecture: fcn
  hidden_sizes: [10, 1]
  dim_input: ${model.D}
  activation: elu
  last_activation: id

dist_configs:
  distribution: normal

flow_configs:
  D: ${model.D}
  flow_seq: []
  act_seq: []

simulation: True
optimizer: adam
learning_rate: 0.01