_target_: src.datamodules.binmnist.BinaryMNISTDataModule

name: binmnist

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 512
val_split: 0.1
num_workers: 16
pin_memory: False
flatten: True