_target_: src.datamodules.mnist.MNISTDataModule

name: mnist

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 512
train_val_test_split: [0.85, 0.05, 0.1]
num_workers: 16
pin_memory: False
normalize: False
flatten: True